package de.rub.rke.randomoracle;

import de.rub.rke.variables.KeySeed;
import de.rub.rke.variables.SymmetricKey;

/**
 * Interface for the output generated by the keyed random oracle
 * 
 * @author Marco Smeets
 *
 */
public interface KeyedRandomOracleOutput {

	/**
	 * @return session key
	 */
	public SymmetricKey getSessionKey();

	/**
	 * @return seed for secret key generation
	 */
	public KeySeed getSecretKeySeed();
}
