package de.rub.rke.kem;

import de.rub.rke.variables.SymmetricKey;

/**
 * Interface for the Output of a Kem
 * 
 * @author Marco Smeets
 *
 */
public interface KemOutput {

	/**
	 * @return symmetric key generated by a Kem
	 */
	public SymmetricKey getKey();

	/**
	 * @return ciphertext that is computed by a Kem
	 */
	public KemCiphertext getCiphertext();
}
