package de.rub.rke.test.fakealgorithmset.mockkukem;

import de.rub.rke.kukem.KuKemCiphertext;
import de.rub.rke.kukem.KuKemPublicKey;

/**
 * Implementation of KuKemCiphertext for the mock kuKem
 * 
 * The ciphertext simply saves the public key used for encapsulation and the
 * keyid generated by the kuKem.
 * 
 * @author Marco Smeets
 *
 */
public class MockKuKemCiphertext implements KuKemCiphertext {

	int keyid;
	MockKuKemPublicKey publicKey;

	public MockKuKemCiphertext(KuKemPublicKey publicKey, int keyid) {
		this.publicKey = (MockKuKemPublicKey) publicKey;
		this.keyid = keyid;
	}

	public int getKeyId() {
		return keyid;
	}

	public KuKemPublicKey getEncryptionKey() {
		return publicKey;
	}

	/**
	 * We use the int encoding throughout the test classes to easily compare two
	 * values.
	 * 
	 * @return
	 */
	public int[] getIntEncoding() {
		int[] encoding = new int[2];
		encoding[0] = keyid;
		encoding[1] = publicKey.getId();
		return encoding;
	}
}
