/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_rub_rkeinstantiation_hibewrapper_Hibe */

#ifndef _Included_de_rub_rkeinstantiation_hibewrapper_Hibe
#define _Included_de_rub_rkeinstantiation_hibewrapper_Hibe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_rub_rkeinstantiation_hibewrapper_Hibe
 * Method:    getSizeOfBnModZp
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_rub_rkeinstantiation_hibewrapper_Hibe_getSizeOfBnModZp
  (JNIEnv *, jclass);

/*
 * Class:     de_rub_rkeinstantiation_hibewrapper_Hibe
 * Method:    getSizeOfG1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_rub_rkeinstantiation_hibewrapper_Hibe_getSizeOfG1
  (JNIEnv *, jclass);

/*
 * Class:     de_rub_rkeinstantiation_hibewrapper_Hibe
 * Method:    getSizeOfG2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_rub_rkeinstantiation_hibewrapper_Hibe_getSizeOfG2
  (JNIEnv *, jclass);

/*
 * Class:     de_rub_rkeinstantiation_hibewrapper_Hibe
 * Method:    getSizeOfGT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_rub_rkeinstantiation_hibewrapper_Hibe_getSizeOfGT
  (JNIEnv *, jclass);

/*
 * Class:     de_rub_rkeinstantiation_hibewrapper_Hibe
 * Method:    getSizeOfuncompressedGT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_rub_rkeinstantiation_hibewrapper_Hibe_getSizeOfuncompressedGT
  (JNIEnv *, jclass);

/*
 * Class:     de_rub_rkeinstantiation_hibewrapper_Hibe
 * Method:    getRandomGtElement
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_rub_rkeinstantiation_hibewrapper_Hibe_getRandomGtElement
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     de_rub_rkeinstantiation_hibewrapper_Hibe
 * Method:    setup
 * Signature: ([BI[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_rub_rkeinstantiation_hibewrapper_Hibe_setup
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray);

/*
 * Class:     de_rub_rkeinstantiation_hibewrapper_Hibe
 * Method:    encrypt
 * Signature: ([B[B[BII[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_rub_rkeinstantiation_hibewrapper_Hibe_encrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     de_rub_rkeinstantiation_hibewrapper_Hibe
 * Method:    decrypt
 * Signature: ([B[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_rub_rkeinstantiation_hibewrapper_Hibe_decrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint);

/*
 * Class:     de_rub_rkeinstantiation_hibewrapper_Hibe
 * Method:    delegate
 * Signature: ([B[BII[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_rub_rkeinstantiation_hibewrapper_Hibe_delegate
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
